all:
  hosts:
    minecraft_server:
      ansible_host: 52.26.193.114
      ansible_user: ec2-user
      ansible_ssh_private_key_file: "${HOME}/.ssh/minecraft_key"
      ansible_ssh_common_args: '-o StrictHostKeyChecking=no'